name: Check Whitespace

on:
  push:
    branches:
      - main
      - development

jobs:
  check_whitespace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get previous commit hash
      run: |
        PREVIOUS_COMMIT=$(git rev-parse HEAD^1)
        echo "PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $GITHUB_ENV

    - name: Check for Whitespace Changes
      run: |
        # Exit with an error if any whitespace changes are detected
        if git diff --check $PREVIOUS_COMMIT ${{ github.sha }}; then
          echo "No whitespace changes detected."
        else
          echo "Error: Whitespace changes detected in the commit. Please remove them and try again."
          exit 1
        fi